avoid-breaking-exported-api = false

allow-unwrap-in-tests = true
allow-expect-in-tests = true
allow-panic-in-tests = true
allow-dbg-in-tests = true
allow-print-in-tests = true
allow-indexing-slicing-in-tests = true

semicolon-inside-block-ignore-singleline = true
semicolon-outside-block-ignore-multiline = true
