[pretty]
    single     =  "format:%>|(9)%C(bold #100F0F #E8705F) %h %C(reset)%C(#100F0F #A0AF54) %cd %C(reset)%C(bold #CECDC3 #100F0F) %s %C(reset)%>|(-2)%C(auto)%d%C(reset) %C(#66A0C8)%G?%C(reset)"
    single-alt =  "format:%C(bold #100F0F #E8705F) %h %C(reset)%C(#100F0F #A0AF54) %cd %C(reset)%C(bold #CECDC3 #100F0F) %s %C(reset)%>|(-2)%C(auto)%d%C(reset) %C(#66A0C8)%G?%C(reset)%n"
    multi      =  "format:Commit    %C(bold #100F0F #E8705F) %H %C(reset)%C(auto)%d%C(reset)%nParent(s) %C(#100F0F #DFB431) %P %C(reset)%nAuthor    %C(#100F0F #BEC97E) %ad %C(reset) %C(#87D3C3)%aN <%aE>%C(reset) %C(#BEC97E)(%ar)%C(reset)%nCommitter %C(#100F0F #A0AF54) %cd %C(reset) %C(#5ABDAC)%cN <%cE>%C(reset) %C(#A0AF54)(%cr)%C(reset)%nSignature %C(bold #100F0F #66A0C8) %G? %C(reset) %C(#66A0C8)with key%C(reset) %C(#100F0F #66A0C8) %GF %C(reset)%n%n%B%n"


[alias]
    lg   = log --date-order --graph --decorate=short --date=format:'%Y-%m-%d %H'          --format=single
    lgf  = log --date-order --graph --decorate=full  --date=format:'%Y-%m-%d %H:%M:%S %z' --format=multi
    lgd  = lg  --stat --full-diff --format=single-alt
    lgfd = lgf --patch
    lga  = lg  --all
    lgad = lgd --all

    ba  = branch --verbose --verbose --all
    bas = branch --verbose --verbose --all --sort=-committerdate

    s  = status --short
    sl = status --long

    a  = add --verbose
    aa = add --verbose --all
    ap = add --patch

    d   = diff
    ds  = diff --stat
    dc  = diff --cached
    dcs = diff --cached --stat
    dni = diff --no-index

    cm  = commit --message
    cms = commit --gpg-sign --message
    cn  = commit --allow-empty-message --message ''
    cns = commit --gpg-sign --allow-empty-message --message ''
    ca  = commit --amend
    cas = commit --gpg-sign --amend

    m   = merge
    ms  = merge --gpg-sign
    mnc = merge --no-commit
    mff = merge --ff-only
    mnf = merge --no-ff

    fap = fetch --all --prune
    pff = pull --ff-only
    pnf = pull --no-ff

    p   = push
    pa  = push --all
    pf  = push --force-with-lease

    # shallow clone
    cls = clone --depth=1 --recurse-submodules --shallow-submodules
    # shallow clone without submodules
    clsns = clone --depth=1
