[init]
    defaultBranch = trunk


[core]
    ignoreCase = false

    safecrlf = warn
    autocrlf = input


[diff]
    colorMoved = default
[merge]
    conflictStyle = zdiff3




[alias]
    lg = log --decorate=short --author-date-order --graph --date=format:'%F' --format=format:'%>|(9)%C(bold reverse 167) %h %C(120) %ad %C(no-reverse) > %Creset%<(65,trunc)%s%C(bold 229)%d%C(81) <%an>%C(nobold) %G?'
    lga = lg --all
    lgd = log --decorate=short --author-date-order --graph --date=format:'%F' --stat --full-diff --format=format:'%C(bold reverse 167) %h %C(120) %ad %C(no-reverse) > %Creset%<(65,trunc)%s%C(bold 229)%d%C(81) <%an>%C(nobold) %G?%n'
    lgf = log --decorate=full --author-date-order --graph --date=format:'%F %T %z' --format=format:'%C(bold 167)Commit     :%C(reverse) %H %C(no-reverse 229)%d%n%C(bold 120)Author Date:%C(reverse) %ad %C(no-reverse) (%ar)%n%C(bold 229)Parent     :%C(reverse) %P %C(no-reverse)%n%C(bold 81)Author     : %an <%ae>%C(nobold) %G?%n%n%B%n'
    lgfd = lgf --patch --full-diff

    ba  = branch --verbose --verbose --all
    bas = branch --verbose --verbose --all --sort=-committerdate

    s  = status --short
    sl = status --long

    a  = add --verbose
    aa = add --verbose --all
    ap = add --patch

    d   = diff
    ds  = diff --stat
    dc  = diff --cached
    dcs = diff --cached --stat
    dni = diff --no-index

    skip-add = update-index --skip-worktree
    skip-remove = update-index --no-skip-worktree
    skip-list = ls-files -v . | grep ^S

    cm  = commit --message
    cms = commit --gpg-sign --message
    cn  = commit --allow-empty-message --message ''
    cns = commit --gpg-sign --allow-empty-message --message ''
    ca  = commit --amend
    cas = commit --gpg-sign --amend

    m   = merge
    ms  = merge --gpg-sign
    mnc = merge --no-commit
    mff = merge --ff-only
    mnf = merge --no-ff

    p   = push
    pa  = push --all
    pf  = push --force-with-lease

    fap = fetch --all --prune
    pff = pull --ff-only
    pnf = pull --no-ff

    # blobless clone
    clbl = clone --filter=blob:none
    # shallow clone
    cls = clone --depth=1 --recurse-submodules --shallow-submodules
    # shallow clone without submodules
    clsns = clone --depth=1

