[core]
    pager = delta
[interactive]
    diffFilter = delta --color-only


[delta]
    navigate = true
    dark = true
    diff-highlight = true
    file-style = yellow
    file-decoration-style = blue box ul
    hunk-header-style = line-number syntax
    hunk-header-decoration-style = blue box
    zero-style = syntax
    keep-plus-minus-markers = true
    line-numbers = true
    line-numbers-minus-style = red
    line-numbers-zero-style = 253
    line-numbers-plus-style = green
