"$schema" = 'https://starship.rs/config-schema.json'

format = """
[>](bold 213) $username $hostname $os $shell $time $status [:](7)
[-](bold 213) $directory(
[-](bold 213) ($git_branch )($git_commit )($git_state )$git_status)
$character """
add_newline = true

[username]
    show_always = true
    format = "[$user]($style)"
    style_user = "bold 81"
    style_root = "bold red"

[hostname]
    ssh_only = false
    format = "[[@$ssh_symbol](7) $hostname]($style)"
    style = "bold 84"
    ssh_symbol = "⇌"

[os]
    disabled = false
    format = "[{$symbol( $version)}]($style)"
    style = "7"
    [os.symbols]
        Unknown = "OS?"

        Linux = "Linux?"
        Windows = "Windows"
        Macos = "macOS"

        Debian = "Debian"
        openSUSE = "openSUSE"

[shell]
    disabled = false
    format = "[{$indicator}]($style)"
    style = "7"
    bash_indicator = "Bash"
    powershell_indicator = "PowerShell"

[time]
    disabled = false
    format = "[\\[$time\\]]($style)"
    style = "15"
    time_format = "%Y-%m-%d %a %H:%M:%S %:z"

[status]
    disabled = false
    format = "[\\([$status]($style)\\)](7)"
    success_symbol = " "
    recognize_signal_code = false

[directory]
    truncation_length = 0
    truncate_to_repo = false
    format = "([$read_only]($read_only_style) )[$path]($style)"
    repo_root_format = "([$read_only]($read_only_style) )[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)"
    style = "229"
    repo_root_style = "bold 229"
    read_only = "[RO]"

[git_branch]
    format = "[$symbol $branch( : $remote_name/$remote_branch)]($style)"
    style = "bold"
    always_show_remote = true
    symbol = ""

[git_commit]
    format = "[\\($hash\\)( \\[$tag\\])]($style)"
    only_detached = true
    tag_disabled = false
    tag_symbol = ""

[git_state]
    format = "\\([$state( $progress_current/$progress_total)]($style)\\)"

[git_status]
    format = "([\\[( $all_status )$ahead_behind\\]]($style))"

    up_to_date = ""
    ahead = "⇡$count"
    behind = "⇣$count"
    diverged = "$ahead_count⇡⇣$behind_count"

    deleted = "✖"

[character]
    format = "$symbol"
    success_symbol = "[\\$](bold 202)"
    error_symbol = "[\\$](bold yellow)"
