# see `https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-rgb-colour`
set-option -ga terminal-features ',*-256color:RGB' # set `RGB` terminfo flag
set-option -ga terminal-overrides ',*-256color:Tc' # set `Tc` tmux flag

# change $TERM because strangely vim does not show color when it is `tmux-256color`
set-option -g default-terminal 'xterm-256color'

# fix Home/End key not functioning (after setting $TERM?)
# see `https://stackoverflow.com/a/55616731`
bind-key -n Home send-keys Escape 'OH'
bind-key -n End send-keys Escape 'OF'

set-option -g status-interval '7'
set-option -g mouse 'on'

#>>>>>> from `https://github.com/egel/tmux-gruvbox`, but removed powerline symbols
## COLORSCHEME: gruvbox dark (medium)

# pane border
set-option -g pane-active-border-style fg=colour250 #fg2
set-option -g pane-border-style fg=colour237 #bg1

# message infos
set-option -g message-style bg=colour239,fg=colour223 # bg=bg2, fg=fg1

# writing commands inactive
set-option -g message-command-style bg=colour239,fg=colour223 # bg=bg2, fg=fg1

# pane number display
set-option -g display-panes-active-colour colour250 #fg2
set-option -g display-panes-colour colour237 #bg1

# clock
set-window-option -g clock-mode-colour colour109 #blue

# status line
set-option -g status 'on'
set-option -g status-justify 'left'
set-option -g status-style bg=colour237,fg=colour223 # bg=bg1, fg=fg1

set-option -g status-left-style none
set-option -g status-left-length '80'
# mode indicator referenced from `https://github.com/MunifTanjim/tmux-mode-indicator`
set-option -g status-left '#[bg=color248,fg=color237]#{?client_prefix,#[bg=color142#,bold] PRFX ,#{?pane_in_mode,#[bg=color208#,bold] COPY ,#{?pane_synchronized,#[bg=color167#,bold] SYNC , TMUX }}}#[bg=colour241,fg=colour248,nobold] #S #[bg=colour237] '

set-option -g status-right-style none
set-option -g status-right-length '80'
set-option -g status-right '#[bg=colour239,fg=colour246] %F %a %T %z #[bg=colour248,fg=colour237] #{user} @ #{host_short} '

set-window-option -g window-status-style bg=colour214,fg=colour237 # bg=yellow, fg=bg1
set-window-option -g window-status-activity-style bg=colour237,fg=colour248 # bg=bg1, fg=fg3
set-window-option -g window-status-bell-style bg=colour167,fg=colour235 # bg=red, fg=bg0
set-window-option -g window-status-format '#[bg=colour239,fg=colour223] #I | #W #[bg=colour237] '

set-window-option -g window-status-separator ''

set-window-option -g window-status-current-style bg=red,fg=colour237 # fg=bg1
set-window-option -g window-status-current-format '#[bg=colour214,fg=colour239] #I |#[bold] #W#{?window_zoomed_flag,*Z,} #[bg=colour237,nobold] '

# vim: set ft=tmux tw=0 nowrap:
#<<<<<<
