" internal encoding
set encoding=utf-8
" file encoding try list (this still won't work well, see:
" https://edyfox.codecarver.org/html/vim_fileencodings_detection.html
" and the `fencview` plugin)
set fileencodings=ucs-bom,utf-8,prc,taiwan,japan,korea,latin1

" end of line/file (see:
" https://vimhelp.org/editing.txt.html#eol-and-eof )
set fileformats=unix,dos
set fixendofline

" indentation (see:
" https://vimhelp.org/usr_30.txt.html#30.5 )
set tabstop=8
set expandtab
set shiftwidth=4
set softtabstop=-1
"
set autoindent
set nosmarttab
"
set breakindent

" persistent undo history
set undodir=.
set undofile
set undolevels=512


" space visibility
set list
set listchars=tab:\|-,trail:-,nbsp:~,precedes:<,extends:>

" always show status line
set laststatus=2

" gutter line number
set number
" cursor position in status line
set ruler
" column wrap guides
set colorcolumn=81,101,121

" cursor line highlight
set cursorline
set cursorlineopt=screenline,number

" cursor to edge
set scrolloff=3
set sidescrolloff=10
set scrolljump=1
set sidescroll=1


" no soft wrap by default
set nowrap
" wrap at word boundary
set linebreak
" no hard wrap
set textwidth=0
set wrapmargin=0

" keys to move over line boundary
set whichwrap=b,s,<,>,[,]


" file type detection and syntax highlight
set t_Co=256
set termguicolors
filetype plugin indent on
syntax enable


"" colorscheme legacy
"colorscheme delek

" colorscheme bright
set background=light
colorscheme wildcharm

"" colorscheme light
"set background=light
"colorscheme retrobox

"" colorscheme dark
"set background=dark
"colorscheme retrobox

"" colorscheme dark alt
"colorscheme sorbet

"" colorscheme contrast
"set background=dark
"colorscheme wildcharm
